name: 'Setup .NET Enviroment'
author: 'Sleepy Star Farm'
description: 'Custom .NET Setup Workflow'

inputs:
  REGISTRY:
    description: 'Optional package source for which to set up authentication. Default is `https://api.nuget.org/v3/index.json`.'
    required: false
    default: 'https://api.nuget.org/v3/index.json'

runs:
  using: 'composite'
  steps:
    - uses: Sleepy-Star-Farm/.github/actions/checkout@dev
    - name: Set up .NET Environment...
      uses: actions/setup-dotnet@v4
      with:
        source-url: ${{ inputs.REGISTRY }}